CREATE TABLE TN_IDP_GROUP (
	IDP_GROUP_SN BIGINT auto_increment NOT NULL COMMENT 'IDP GROUP 고유일련번호',
	IDP_GROUP_NM VARCHAR(50) NULL COMMENT 'IDP GROUP 이름',
	IDP_GROUP_STATUS varchar(1) DEFAULT 1 NULL COMMENT 'IDP GROUP 상태 (1 : 정상 , 2 : 잠금 , 9 : 탈퇴)',
	REMARKS varchar(255) NULL COMMENT '비고',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	MOD_SN BIGINT NULL COMMENT '변경자 고유일련번호',
	MOD_DT DATETIME NULL COMMENT '변경 일시',
	DEL_SN BIGINT NULL COMMENT '삭제자 고유일련번호',
	DEL_DT DATETIME NULL COMMENT '삭제 일시',
	CONSTRAINT TN_IDP_GROUP_PK PRIMARY KEY (IDP_GROUP_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='IDP GROUP 테이블'
;


CREATE TABLE TM_IDP_ADDITIONAL_FEATURE (
	IDP_GROUP_SN BIGINT NOT NULL COMMENT 'IDP GROUP 고유일련번호 (TN_IDP_GROUP.IDP_GROUP_SN)',
	LOGIN_FAILURE_CNT INT DEFAULT 5 NULL COMMENT '로그인 실패 허용 횟수',
	LOGIN_LOCK_TIMED VARCHAR(10) DEFAULT 10 NULL COMMENT '로그인 제한 시간 (단위 : M)',
	REGISTRATION_ALLOWED VARCHAR(1) DEFAULT 'N' NULL COMMENT '회원가입 허용 여부 (Y : 허용 , N : 미허용)',
	RESET_PASSWORD_ALLOWED VARCHAR(1) DEFAULT 'N' NULL COMMENT '패스워드 초기화 허용 여부 (Y : 허용 , N : 미허용)',
	REMEMBER_USER_ID_ALLOWED VARCHAR(1) DEFAULT 'N' NULL COMMENT '아이디 기억하기 허용 여부 (Y : 허용 , N : 미허용)',
	CONSTRAINT TM_IDP_ADDITIONAL_FEATURE_PK PRIMARY KEY (IDP_GROUP_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='IDP 부가 기능 Mapping 테이블'
;


CREATE TABLE TM_IDP_PROVIDER (
	IDP_GROUP_SN BIGINT NOT NULL COMMENT 'TN_CLIENT.CLIENT_SN',
	LOGIN_URL VARCHAR(255) NOT NULL COMMENT '로그인 URL',
	AUTHORIZATION_CODE_URI varchar(255) NOT NULL COMMENT '코드 발급 경로',
	TOKEN_URI varchar(255) NOT NULL COMMENT '토큰 발급 경로',
	USER_INFO_URI varchar(255) NULL COMMENT '사용자 정보 경로',
	JWK_SET_URI varchar(255) NULL COMMENT 'IDP 공개키 경로',
	USER_NAME_ATTRIBUTE_NM varchar(30) DEFAULT 'sub' NULL COMMENT '사용자 식별 클레임 이름'
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='IDP 공급자 정보 Mapping 테이블'
;


CREATE TABLE TN_CLIENT (
	CLIENT_SN BIGINT auto_increment NOT NULL COMMENT '클라이언트 고유일련번호',
	IDP_GROUP_SN BIGINT NOT NULL COMMENT 'IDP GROUP 고유일련번호 (TN_IDP_GROUP.IDP_GROUP_SN)',
	CLIENT_ID varchar(50) NOT NULL COMMENT '클라이언트 ID',
	CLIENT_SECRET varchar(255) NOT NULL COMMENT '클라이언트 시크릿 (client_secret_jwt)',
	CLIENT_SECRET_HASH varchar(255) NULL COMMENT '클라이언트 시크릿 해시 (client_secret_basic, client_secret_post)',
	CLIENT_NM VARCHAR(30) NOT NULL COMMENT '클라이언트 이름',
	CLIENT_STATUS varchar(1) NOT NULL COMMENT '클라이언트 상태 (1 : 정상 , 2 : 잠금 , 9 : 삭제)',
	REMARKS varchar(255) NULL COMMENT '비고',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	MOD_SN BIGINT NULL COMMENT '변경자 고유일련번호',
	MOD_DT DATETIME NULL COMMENT '변경 일시',
	DEL_SN BIGINT NULL COMMENT '삭제자 고유일련번호',
	DEL_DT DATETIME NULL COMMENT '삭제 일시',
	CONSTRAINT TN_CLIENT_PK PRIMARY KEY (CLIENT_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='클라이언트 정보 테이블'
;


CREATE TABLE TM_CLIENT_SETTING (
	CLIENT_SN BIGINT NOT NULL COMMENT '클라이언트 고유일련번호',
	CLIENT_AUTHENTICATION_METHODS varchar(255) NOT NULL COMMENT '클라이언트 인증 방식',
	AUTHORIZED_GRANT_TYPES varchar(255) DEFAULT 'authorization_code,refresh_token' COMMENT '허가된 인증방식',
	REDIRECT_URIS varchar(2000) NULL COMMENT '로그인 후 리다이렉션 URI 목록',
	POST_LOGOUT_REDIRECT_URIS varchar(2000) NULL COMMENT '로그아웃 후 리다이렉션 URI 목록',
	REQUIRE_AUTHORIZATION_CONSENT varchar(1) DEFAULT 'N' NULL COMMENT '인가 동의 요구 여부 (Y : 허용 , N : 미허용)',
	REQUIRE_PROOF_KEY varchar(1) DEFAULT 'N' NULL COMMENT 'PKCE 요구 여부 (Y : 허용 , N : 미허용)',
	JWK_SET_URL varchar(1000) NULL COMMENT '클라이언트 공개키 경로',
	TOKEN_ENDPOINT_AUTHENTICATION_SIGNING_ALGORITHM varchar(100) NULL COMMENT '토큰 엔드포인트 인증 서명 알고리즘',
	`ACCESS_TOKEN_LIFE_SPAN` BIGINT DEFAULT 3600 NULL COMMENT '엑세스 토큰 유효 기간 (단위: S)',
	`REFRESH_TOKEN_LIFE_SPAN` BIGINT DEFAULT 86400 NULL COMMENT '리프레시 토큰 유효 기간 (단위: S)',
	REUSE_REFRESH_TOKENS varchar(1) DEFAULT 'N' NULL COMMENT '리프레시 토큰 재사용 여부 (Y : 허용 , N : 미허용)',
	ID_TOKEN_SIGNATURE_ALGORITHM varchar(100) NOT NULL COMMENT 'ID 토큰 서명 알고리즘',
	AUTHORIZATION_CODE_LIFE_SPAN BIGINT DEFAULT 300 NULL COMMENT '인가 코드 유효기간 (단위: S)',
	BACKCHANNEL_LOGOUT_URI varchar(1000) NULL COMMENT 'Back-Channel Logout URI',
	BACKCHANNEL_LOGOUT_SESSION_REQUIRED varchar(1) DEFAULT 'N' NULL COMMENT 'Back-Channel Logout 세션 요구 여부',
	CONSTRAINT TM_CLIENT_SETTING_PK PRIMARY KEY (CLIENT_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='클라이언트 설정 정보 Mapping 테이블'
;


CREATE TABLE TN_SCOPE (
	SCOPE_SN BIGINT auto_increment NOT NULL COMMENT '허용 범위 고유일련번호',
	SCOPE_NM varchar(50) NOT NULL COMMENT '허용 범위 이름',
	ASSIGNED_TYPE varchar(1) DEFAULT '2' NULL COMMENT '지정 유형 (1 : Default , 2 : Optional)',
	DESCRIPTION varchar(255) NULL COMMENT '설명',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	MOD_SN BIGINT NULL COMMENT '변경자 고유일련번호',
	MOD_DT DATETIME NULL COMMENT '변경 일시',
	DEL_SN BIGINT NULL COMMENT '삭제자 고유일련번호',
	DEL_DT DATETIME NULL COMMENT '삭제 일시',
	CONSTRAINT TN_SCOPE_PK PRIMARY KEY (SCOPE_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='허용 범위 정보 테이블'
;


CREATE TABLE TM_CLIENT_SCOPE (
	CLIENT_SN BIGINT NOT NULL COMMENT '클라이언트 고유일련번호 (TN_CLIENT.CLIENT_SN)',
	SCOPE_SN BIGINT NOT NULL COMMENT '허용 범위 고유일련번호 (TN_SCOPE.SCOPE_SN)',
	CONSTRAINT TM_CLIENT_SCOPE_PK PRIMARY KEY (CLIENT_SN,SCOPE_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='클라이언트 허용 범위 Mapping 테이블'
;


CREATE TABLE TN_RESOURCE_SERVER (
	RESOURCE_SERVER_SN BIGINT auto_increment NOT NULL COMMENT '리소스 서버 고유일련번호',
	RESOURCE_SERVER_NM varchar(50) NOT NULL COMMENT '리소스 서버 이름',
	RESOURCE_SERVER_URI varchar(255) NULL COMMENT '리소스 서버 URI',
	RESOURCE_SERVER_IP varchar(30) NOT NULL COMMENT '리소스 서버 IP',
	DESCRIPTION varchar(255) NULL COMMENT '설명',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	MOD_SN BIGINT NULL COMMENT '변경자 고유일련번호',
	MOD_DT DATETIME NULL COMMENT '변경 일시',
	DEL_SN BIGINT NULL COMMENT '삭제자 고유일련번호',
	DEL_DT DATETIME NULL COMMENT '삭제 일시',
	CONSTRAINT TN_RESOURCE_SERVER_PK PRIMARY KEY (RESOURCE_SERVER_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='리소스 서버 정보 테이블'
;


CREATE TABLE TM_CLIENT_RESOURCE_SERVER (
	CLIENT_SN BIGINT NOT NULL COMMENT '클라이언트 고유일련번호 (TN_CLIENT.CLIENT_SN)',
	RESOURCE_SERVER_SN BIGINT NOT NULL COMMENT '리소스 서버 고유일련번호 (TN_RESOURCE_SERVER.RESOURCE_SERVER_SN)',
	CONSTRAINT TM_CLIENT_RESOURCE_SERVER_PK PRIMARY KEY (CLIENT_SN,RESOURCE_SERVER_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='클라이언트 리소스 서버 Mapping 테이블'
;


CREATE TABLE TN_USER (
	USER_SN BIGINT auto_increment NOT NULL COMMENT '사용자 고유일련번호',
	IDP_GROUP_SN BIGINT NOT NULL COMMENT 'IDP GROUP 고유일련번호 (TN_IDP_GROUP.IDP_GROUP_SN)',
	USER_ID varchar(30) NOT NULL COMMENT '사용자 ID',
	USER_NM varchar(30) NULL COMMENT '사용자 이름',
	PASSWORD varchar(255) NOT NULL COMMENT '사용자 패스워드',
	MOBILE varchar(255) NULL COMMENT '휴대폰 번호',
	EMAIL VARCHAR(50) NULL COMMENT '이메일',
	EMAIL_AUTH_YN varchar(1) DEFAULT '2' NULL COMMENT '이메일 인증 여부 (Y : 인증 , N : 미인증)',
	USER_TYPE varchar(1) NOT NULL COMMENT '사용자 유형 (1 : 정상 , 2 : 미인증)',
	USER_STATUS VARCHAR(1) DEFAULT '1' NULL COMMENT '사용자 상태 (1 : 정상 , 2 : 잠금 , 9 : 탈퇴)',
	LOGIN_FAILURE_CNT INT(1) DEFAULT 0 NULL COMMENT '로그인 실패 횟수',
	PASSWORD_MOD_DT DATETIME NULL COMMENT '패스워드 수정 일시',
	LOGIN_LAST_DT DATETIME NULL COMMENT '최근 로그인 일시',
	REMARKS varchar(255) NULL COMMENT '비고',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	MOD_SN BIGINT NULL COMMENT '변경자 고유일련번호',
	MOD_DT DATETIME NULL COMMENT '변경 일시',
	DEL_SN BIGINT NULL COMMENT '삭제자 고유일련번호',
	DEL_DT DATETIME NULL COMMENT '삭제 일시',
	CONSTRAINT TN_USER_PK PRIMARY KEY (USER_SN),
	CONSTRAINT TN_USER_UNIQUE UNIQUE KEY (IDP_GROUP_SN,USER_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='사용자 정보 테이블'
;


CREATE TABLE TN_ROLE (
	ROLE_SN BIGINT auto_increment NOT NULL COMMENT '역할 고유일련번호',
	ROLE_NM varchar(30) NOT NULL COMMENT '역할 이름',
	ROLE_STATUS varchar(1) NOT NULL COMMENT '역할 상태 (1 : 사용 , 2 : 미사용)',
	REMARKS varchar(255) NULL COMMENT '비고',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	MOD_SN BIGINT NULL COMMENT '변경자 고유일련번호',
	MOD_DT DATETIME NULL COMMENT '변경 일시',
	DEL_SN BIGINT NULL COMMENT '삭제자 고유일련번호',
	DEL_DT DATETIME NULL COMMENT '삭제 일시',
	CONSTRAINT TN_ROLE_PK PRIMARY KEY (ROLE_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='역할 정보 테이블'
;


CREATE TABLE TM_USER_ROLE (
	USER_SN BIGINT NOT NULL COMMENT '사용자 고유일련번호 (TN_USER.USER_SN)',
	ROLE_SN BIGINT NOT NULL COMMENT '역할 고유일련번호 (TN_ROLE.ROLE_SN)',
	CONSTRAINT TM_USER_ROLE_PK PRIMARY KEY (USER_SN,ROLE_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='사용자 역할 Mapping 테이블'
;


CREATE TABLE TH_USER_AUTH (
	UAH_SN BIGINT auto_increment NOT NULL COMMENT '사용자 인증 이력 고유일련번호',
	UAH_TYPE varchar(1) NOT NULL COMMENT '인증 유형 (1 : 로그인 , 2 : 로그아웃 , 3 : 실패)',
	USER_SN BIGINT NOT NULL COMMENT '사용자 고유일련번호 (TN_USER.USER_SN)',
	USER_TYPE varchar(1) NOT NULL COMMENT '사용자 유형 (TN_USER.USER_TYPE)',
	CONNECT_IP varchar(30) NOT NULL COMMENT '접속 IP',
	USERAGENT varchar(255) NOT NULL COMMENT 'USERAGENT',
	FAIL_REASON varchar(255) NULL COMMENT '실패 사유',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '생성 일시',
	CONSTRAINT TH_USER_AUTH_PK PRIMARY KEY (UAH_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='사용자 인증 이력 테이블'
;

CREATE TABLE TH_CHANGE (
	MH_SN BIGINT auto_increment NOT NULL COMMENT '변경 이력 고유일련번호',
	MH_TYPE varchar(1) NOT NULL COMMENT '변경 유형 (1 : 저장 , 2 : 수정 , 3 : 삭제)',
	TARGET varchar(30) NOT NULL COMMENT '변경 대상',
	TARGET_TYPE varchar(1) NOT NULL COMMENT '변경 대상 유형',
	MH_ORI_VAL varchar(255) NOT NULL COMMENT '변경 전 데이터',
	MH_MOD_VAL varchar(255) NULL COMMENT '변경 후 데이터',
	REG_SN BIGINT NULL COMMENT '등록자 고유일련번호 (TN_USER.USER_SN)',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	CONSTRAINT TH_CHANGE_PK PRIMARY KEY (MH_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='변경 이력 테이블'
;


CREATE TABLE TC_CODE (
	CD_SN BIGINT auto_increment NOT NULL COMMENT '코드 고유일련번호',
	CG_SN BIGINT NOT NULL COMMENT '코드그룹 고유일련번호',
	CD_ID varchar(10) NOT NULL COMMENT '코드 ID',
	CD_NM varchar(100) NULL COMMENT '코드 이름',
	CD_STATUS varchar(1) DEFAULT '1' NOT NULL COMMENT '코드 상태 (0 : 미사용 , 1 : 사용 , 2 : 항목제외)',
	CD_ORDER INT NULL COMMENT '정렬 순서',
	CD_REMARK varchar(255) NULL COMMENT '코드 비고 / 설명',
	REG_DT DATETIME DEFAULT CURRENT_TIMESTAMP NULL COMMENT '등록 일시',
	CONSTRAINT TC_CODE_PK PRIMARY KEY (CD_SN)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='공통코드 테이블'
;