# TEST IDP GROUP 생성
INSERT INTO TN_IDP_GROUP(IDP_GROUP_NM, IDP_GROUP_STATUS, REMARKS, REG_SN)
VALUES ('IdP', '1', '테스트 IdP 서버', '0')
;

INSERT INTO TM_IDP_ADDITIONAL_FEATURE(IDP_GROUP_SN)
VALUES ((SELECT IDP_GROUP_SN
		FROM TN_IDP_GROUP
		WHERE IDP_GROUP_NM = 'IdP'))
;

# TEST USER 생성
INSERT INTO TN_USER(IDP_GROUP_SN, USER_ID, USER_NM, PASSWORD,
					MOBILE, EMAIL, EMAIL_AUTH_YN, USER_TYPE,
					USER_STATUS, REMARKS, REG_SN)
VALUES ((SELECT IDP_GROUP_SN
		FROM TN_IDP_GROUP
		WHERE IDP_GROUP_NM = 'IdP'), 
		'admin', 
		'관리자', 
		'$2a$12$8WCZVutpas0wI0Bu/1uCUeIVBevo10/brW/UrCD74GzZIWahuQVkW', 
		'',
		'admin@google.com',
		'N',
		'1',
		'1',
		'관리자 (패스워드 : password)',
		'0')
;


# TEST CLIENT 생성
INSERT INTO TN_CLIENT (
    IDP_GROUP_SN, CLIENT_ID, CLIENT_SECRET, CLIENT_NM, CLIENT_STATUS,
    REMARKS, REG_SN
) VALUES (
    (SELECT IDP_GROUP_SN
	 FROM TN_IDP_GROUP
	 WHERE IDP_GROUP_NM = 'IdP'),
    'web-app',
    '$2a$12$8eOmgROvG4tv8EMRvRXDJuBA3sB8MFZDJ1754fntXjGT4hxyZ4mYm',
    '웹 애플리케이션',
    '1',
    '테스트 클라이언트 (PASSWORD: secretpassword123)',
    0)
;

INSERT INTO TM_CLIENT_SETTING (
    CLIENT_SN, CLIENT_AUTHENTICATION_METHODS, REDIRECT_URIS, POST_LOGOUT_REDIRECT_URIS,  
	ID_TOKEN_SIGNATURE_ALGORITHM, BACKCHANNEL_LOGOUT_URI, BACKCHANNEL_LOGOUT_SESSION_REQUIRED
) VALUES (
    (SELECT CLIENT_SN 
	 FROM TN_CLIENT
	 WHERE CLIENT_ID = 'web-app'),
    'client_secret_basic',
    'https://oauth.pstmn.io/v1/callback',
    'https://naver.com',
    'RS256',
    'http://localhost:7555/logout',
    'Y')
;
# TEST SCOPE 생성
INSERT INTO TN_SCOPE(SCOPE_NM, ASSIGNED_TYPE, DESCRIPTION, REG_SN)
VALUES ('openid', '2', 'openid', '0'), 
	   ('profile', '2', 'profile', '0')
;
		
INSERT INTO TM_CLIENT_SCOPE(CLIENT_SN, SCOPE_SN)
VALUES ((SELECT CLIENT_SN
		 FROM TN_CLIENT
		 WHERE CLIENT_ID = 'web-app'),
		(SELECT SCOPE_SN
		 FROM TN_SCOPE
		 WHERE SCOPE_NM = 'openid'))
;