server:
  port: 7555

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    path: ../logs/IdP-server
    name: app-log
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 10MB

security:
  oauth2:
    authorizationserver:
      issuer: http://localhost:7555
